### PR TITLE
fix clang incomplete return type error

### PR DESCRIPTION
**Pull request by avagordon01**
before this change, Auto-Vk doesn't compile with clang 18.1.8, with the following error:
```
In file included from .../avk-test.cc:1:
In file included from .../builddir/_deps/avk-src/include/avk/avk.hpp:223:
.../builddir/_deps/avk-src/include/avk/buffer.hpp:273:4: error: calling 'read_into' with incomplete return type 'avk::command::action_type_command'
  273 |                         read_into(static_cast<void*>(&result), aMetaDataIndex);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../builddir/_deps/avk-src/include/avk/buffer.hpp:255:37: note: 'read_into' declared here
  255 |                 avk::command::action_type_command read_into(void* aDataPtr, size_t aMetaDataIndex) const;
      |                                                   ^
.../builddir/_deps/avk-src/include/avk/avk.hpp:215:10: note: forward declaration of 'avk::command::action_type_command'
  215 |                 struct action_type_command;
      |                        ^
```
there may well be a neater place to put the `read` function definition than in the main `avk.hpp`, but I don't know the codebase

### CODE REVIEW

**Comment by johannesugb** [comment]
Thanks for your contribution.
